## PHASE 1

In [16]:
!pip install feedparser tqdm

Requirement already satisfied: feedparser in /usr/local/lib/python3.12/dist-packages (6.0.12)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.12/dist-packages (from feedparser) (1.0.0)

In [17]:
import pandas as pd
import feedparser
from tqdm import tqdm
from urllib.parse import quote

In [18]:
news_df = pd.read_csv("/cyber_news.csv")

vendor_list = news_df["vendor"].dropna().unique().tolist()

print(len(vendor_list))
print(vendor_list[:10])

36
['AWS', 'Accenture', 'Auth0', 'Check Point', 'Cisco', 'Cloudflare', 'CrowdStrike', 'Databricks', 'Deloitte', 'EY']

In [19]:
queries = {

    "Financial":
    "earnings revenue profit loss quarterly results stock shares acquisition merger IPO guidance",

    "Compliance":
    "SEC penalty regulatory fine lawsuit audit GDPR investigation antitrust compliance",

    "Operational":
    "outage downtime latency service disruption incident availability failure"

}

In [20]:
from urllib.parse import quote
import feedparser

def fetch_news(vendor, category, query):

    query = quote(f"{vendor} {query}")

    rss_url = (
        f"https://news.google.com/rss/search?"
        f"q={query}&hl=en-US&gl=US&ceid=US:en"
    )

    feed = feedparser.parse(rss_url)

    articles = []

    for entry in feed.entries:

        articles.append({

            "vendor": vendor,
            "title": entry.title,
            "link": entry.link,
            "published": getattr(entry,"published",""),
            "category": category

        })

    return articles

In [21]:
from tqdm import tqdm

all_news = []

for vendor in tqdm(vendor_list):

    for category, query in queries.items():

        try:

            all_news.extend(
                fetch_news(
                    vendor,
                    category,
                    query
                )
            )

        except Exception as e:
            pass

100%|██████████| 36/36 [00:27<00:00,  1.32it/s]

In [22]:
extra_news = pd.DataFrame(all_news)

extra_news.drop_duplicates(
    subset=["vendor","title"],
    inplace=True
)

extra_news.reset_index(
    drop=True,
    inplace=True
)

print(extra_news.shape)

(561, 5)

In [23]:
extra_news["category"].value_counts()

category
Operational    480
Financial       81
Name: count, dtype: int64

In [25]:
cyber = pd.read_csv("/cyber_news.csv")

financial = extra_news[
    extra_news["category"]=="Financial"
]

operational = extra_news[
    extra_news["category"]=="Operational"

]

master_news = pd.concat([
    cyber,
    financial,
    operational
])

master_news.drop_duplicates(
    subset=["vendor","title"],
    inplace=True
)

master_news.reset_index(
    drop=True,
    inplace=True
)

print(master_news.shape)

(1418, 12)

In [26]:
master_news.head(10)

,vendor,title,link,published,text,clean_text,risk_category,cyber_hits,financial_hits,compliance_hits,operational_hits,category
0,AWS,Largest Healthcare Data Breaches of 2025 - The...,https://news.google.com/rss/articles/CBMiekFVX...,"Fri, 05 Jun 2026 07:00:00 GMT",Largest Healthcare Data Breaches of 2025 - The...,Largest Healthcare Data Breaches of 2025 - The...,Cybersecurity,1.0,0.0,0.0,0.0,NaN
1,AWS,9 All-Too-Common AWS Security Risks - wiz.io,https://news.google.com/rss/articles/CBMibEFVX...,"Fri, 20 Feb 2026 08:00:00 GMT",9 All-Too-Common AWS Security Risks - wiz.io,9 All-Too-Common AWS Security Risks - wiz io,Cybersecurity,1.0,0.0,1.0,0.0,NaN
2,AWS,LexisNexis AWS Data Breach 2026: React2Shell E...,https://news.google.com/rss/articles/CBMitAFBV...,"Thu, 05 Mar 2026 08:00:00 GMT",LexisNexis AWS Data Breach 2026: React2Shell E...,LexisNexis AWS Data Breach 2026 React2Shell Ex...,Cybersecurity,3.0,0.0,0.0,0.0,NaN
3,AWS,8-Minute Access: AI Accelerates Breach of AWS ...,https://news.google.com/rss/articles/CBMijAFBV...,"Tue, 03 Feb 2026 08:00:00 GMT",8-Minute Access: AI Accelerates Breach of AWS ...,8-Minute Access AI Accelerates Breach of AWS E...,Cybersecurity,1.0,0.0,0.0,0.0,NaN
4,AWS,Supply Chain Cyber Attacks Surge as EU Breach ...,https://news.google.com/rss/articles/CBMiuAFBV...,"Thu, 16 Apr 2026 07:00:00 GMT",Supply Chain Cyber Attacks Surge as EU Breach ...,Supply Chain Cyber Attacks Surge as EU Breach ...,Cybersecurity,3.0,0.0,0.0,0.0,NaN
5,AWS,Hackers Exploit CVE-2025-55182 to Breach 766 N...,https://news.google.com/rss/articles/CBMifEFVX...,"Thu, 02 Apr 2026 07:00:00 GMT",Hackers Exploit CVE-2025-55182 to Breach 766 N...,Hackers Exploit CVE-2025-55182 to Breach 766 N...,Cybersecurity,4.0,0.0,0.0,0.0,NaN
6,AWS,Amazon waives entire month’s AWS charges after...,https://news.google.com/rss/articles/CBMitwFBV...,"Mon, 30 Mar 2026 07:00:00 GMT",Amazon waives entire month’s AWS charges after...,Amazon waives entire month s AWS charges after...,Cybersecurity,1.0,0.0,0.0,0.0,NaN
7,AWS,Agentic AI for Cybersecurity: 10 Use Cases & E...,https://news.google.com/rss/articles/CBMiW0FVX...,"Wed, 20 May 2026 07:00:00 GMT",Agentic AI for Cybersecurity: 10 Use Cases & E...,Agentic AI for Cybersecurity 10 Use Cases Exam...,Cybersecurity,2.0,0.0,1.0,0.0,NaN
8,AWS,Exposed AWS Credentials Lead to AI-Assisted Cl...,https://news.google.com/rss/articles/CBMib0FVX...,"Wed, 04 Feb 2026 08:00:00 GMT",Exposed AWS Credentials Lead to AI-Assisted Cl...,Exposed AWS Credentials Lead to AI-Assisted Cl...,Cybersecurity,2.0,0.0,0.0,0.0,NaN
9,AWS,AWS Security Best Practices: 9 Tips to Secure ...,https://news.google.com/rss/articles/CBMieEFVX...,"Mon, 17 Nov 2025 08:00:00 GMT",AWS Security Best Practices: 9 Tips to Secure ...,AWS Security Best Practices 9 Tips to Secure a...,Cybersecurity,1.0,0.0,1.0,0.0,NaN

In [27]:
master_news["category"].value_counts()

category
Operational    480
Financial       81
Name: count, dtype: int64

In [28]:
master_news["category"].isna().sum()

np.int64(857)

In [31]:
cyber_news = pd.read_csv("/cyber_news.csv")

# Add category manually
cyber_news["category"] = "Cybersecurity"

cyber_news.head()

,vendor,title,link,published,text,clean_text,risk_category,cyber_hits,financial_hits,compliance_hits,operational_hits,category
0,AWS,Largest Healthcare Data Breaches of 2025 - The...,https://news.google.com/rss/articles/CBMiekFVX...,"Fri, 05 Jun 2026 07:00:00 GMT",Largest Healthcare Data Breaches of 2025 - The...,Largest Healthcare Data Breaches of 2025 - The...,Cybersecurity,1,0,0,0,Cybersecurity
1,AWS,9 All-Too-Common AWS Security Risks - wiz.io,https://news.google.com/rss/articles/CBMibEFVX...,"Fri, 20 Feb 2026 08:00:00 GMT",9 All-Too-Common AWS Security Risks - wiz.io,9 All-Too-Common AWS Security Risks - wiz io,Cybersecurity,1,0,1,0,Cybersecurity
2,AWS,LexisNexis AWS Data Breach 2026: React2Shell E...,https://news.google.com/rss/articles/CBMitAFBV...,"Thu, 05 Mar 2026 08:00:00 GMT",LexisNexis AWS Data Breach 2026: React2Shell E...,LexisNexis AWS Data Breach 2026 React2Shell Ex...,Cybersecurity,3,0,0,0,Cybersecurity
3,AWS,8-Minute Access: AI Accelerates Breach of AWS ...,https://news.google.com/rss/articles/CBMijAFBV...,"Tue, 03 Feb 2026 08:00:00 GMT",8-Minute Access: AI Accelerates Breach of AWS ...,8-Minute Access AI Accelerates Breach of AWS E...,Cybersecurity,1,0,0,0,Cybersecurity
4,AWS,Supply Chain Cyber Attacks Surge as EU Breach ...,https://news.google.com/rss/articles/CBMiuAFBV...,"Thu, 16 Apr 2026 07:00:00 GMT",Supply Chain Cyber Attacks Surge as EU Breach ...,Supply Chain Cyber Attacks Surge as EU Breach ...,Cybersecurity,3,0,0,0,Cybersecurity

In [32]:
print(master_news.shape)

print(master_news.columns)

(1418, 12)
Index(['vendor', 'title', 'link', 'published', 'text', 'clean_text',
       'risk_category', 'cyber_hits', 'financial_hits', 'compliance_hits',
       'operational_hits', 'category'],
      dtype='object')

In [33]:
master_news["category"] = master_news["category"].fillna("Cybersecurity")

In [34]:
master_news["category"].value_counts()

category
Cybersecurity    857
Operational      480
Financial         81
Name: count, dtype: int64

In [35]:
vendor_summary = master_news.groupby(

    ["vendor","category"]

).size().unstack(fill_value=0)

vendor_summary

category            Cybersecurity  Financial  Operational
vendor
AWS                            61          6           54
Accenture                       7          2            1
Auth0                           2          0            0
Check Point                    64          5           49
Cisco                          56          4           13
Cloudflare                     37          1           43
CrowdStrike                    47          1           34
Databricks                      5          2            9
Deloitte                       29          0            2
EY                             28          1            0
Fortinet                       40          4            4
Google Cloud                   41         17           53
IBM Cloud                      41          0           11
Infosys                        11          2            6
KPMG                           25          0            1
Mastercard                      6          1            5
Microsoft Azure                29          1           47
MongoDB                         9          0            3
Okta                           23          2            1
Oracle                         58          1           18
Oracle Cloud                   15          0           26
Palo Alto Networks             32          6           16
PayPal                         13          2            8
Ping Identity                   7          0            1
PwC                            22          0            1
Redis                           8          0            3
SAP                            24          2            3
ServiceNow                     14          4            1
Snowflake                      35          5            7
Stripe                          2          0            2
TCS                            13          5           12
Trend Micro                    23          0            1
Visa                            9          2           15
Wipro                           4          1            8
Workday                         4          2           12
Zscaler                        13          2           10

vendor risk score generator:

In [36]:
vendor_summary["risk_score"] = (

      0.50 * vendor_summary.get("Cybersecurity",0)

    + 0.20 * vendor_summary.get("Financial",0)

    + 0.30 * vendor_summary.get("Operational",0)

)

vendor_summary = vendor_summary.sort_values(

    "risk_score",

    ascending=False

)

vendor_summary.head(20)

category            Cybersecurity  Financial  Operational  risk_score
vendor
AWS                            61          6           54        47.9
Check Point                    64          5           49        47.7
Google Cloud                   41         17           53        39.8
Oracle                         58          1           18        34.6
CrowdStrike                    47          1           34        33.9
Cisco                          56          4           13        32.7
Cloudflare                     37          1           43        31.6
Microsoft Azure                29          1           47        28.8
IBM Cloud                      41          0           11        23.8
Fortinet                       40          4            4        22.0
Palo Alto Networks             32          6           16        22.0
Snowflake                      35          5            7        20.6
Oracle Cloud                   15          0           26        15.3
Deloitte                       29          0            2        15.1
EY                             28          1            0        14.2
SAP                            24          2            3        13.3
KPMG                           25          0            1        12.8
Okta                           23          2            1        12.2
Trend Micro                    23          0            1        11.8
PwC                            22          0            1        11.3

In [37]:
master_news.to_csv(
    "master_news.csv",
    index=False
)

vendor_summary.to_csv(
    "vendor_summary.csv"
)

from google.colab import files

# files.download("master_news.csv")
# files.download("vendor_summary.csv")

compliance feed appending:

In [38]:
import random
import pandas as pd
from datetime import datetime, timedelta

In [39]:
vendor_list = master_news["vendor"].unique().tolist()

len(vendor_list)

36

In [40]:
compliance_events = [

    "SEC Investigation Initiated",

    "Regulatory Fine Imposed",

    "GDPR Compliance Review",

    "Audit Observation Raised",

    "Regulatory Warning Notice",

    "Data Protection Inquiry",

    "Compliance Policy Violation",

    "Financial Reporting Irregularity",

    "AML Compliance Investigation",

    "Privacy Compliance Audit",

    "Internal Control Deficiency",

    "Risk Governance Review",

    "Regulatory Filing Delay",

    "SOX Compliance Review",

    "Anti-Trust Investigation"

]

severity_levels = [

    "Low",

    "Medium",

    "High",

    "Critical"

]

In [41]:
rows = []

for i in range(150):

    vendor = random.choice(vendor_list)

    event = random.choice(compliance_events)

    severity = random.choices(

        severity_levels,

        weights=[0.2,0.4,0.3,0.1]

    )[0]

    random_date = (

        datetime.today()

        - timedelta(

            days=random.randint(1,365)

        )

    ).strftime("%Y-%m-%d")

    rows.append({

        "vendor": vendor,

        "title": event,

        "link": "Synthetic Compliance Feed",

        "published": random_date,

        "category": "Compliance",

        "severity": severity

    })

compliance_df = pd.DataFrame(rows)

compliance_df.head()

,vendor,title,link,published,category,severity
0,Google Cloud,Regulatory Filing Delay,Synthetic Compliance Feed,2026-02-23,Compliance,Low
1,Zscaler,SEC Investigation Initiated,Synthetic Compliance Feed,2026-02-14,Compliance,High
2,PwC,SOX Compliance Review,Synthetic Compliance Feed,2026-01-08,Compliance,Low
3,KPMG,Regulatory Warning Notice,Synthetic Compliance Feed,2025-07-05,Compliance,Medium
4,Workday,Privacy Compliance Audit,Synthetic Compliance Feed,2026-06-01,Compliance,High

In [42]:
compliance_df["severity"].value_counts()

severity
Medium      55
High        48
Low         25
Critical    22
Name: count, dtype: int64

In [43]:
master_news = pd.concat(

    [

        master_news,

        compliance_df

    ],

    ignore_index=True

)

In [44]:
master_news["category"].value_counts()

category
Cybersecurity    857
Operational      480
Compliance       150
Financial         81
Name: count, dtype: int64

In [45]:
print(master_news.shape)

(1568, 13)

In [46]:
master_news.to_csv(

    "master_news.csv",

    index=False

)

from google.colab import files

# files.download("master_news.csv")

In [47]:
vendor_summary = master_news.groupby(
    ["vendor", "category"]
).size().unstack(fill_value=0)

vendor_summary.head()

category     Compliance  Cybersecurity  Financial  Operational
vendor
AWS                   7             61          6           54
Accenture             4              7          2            1
Auth0                 3              2          0            0
Check Point           3             64          5           49
Cisco                 4             56          4           13

In [48]:
vendor_summary["risk_score"] = (

      0.40 * vendor_summary.get("Cybersecurity", 0)

    + 0.20 * vendor_summary.get("Financial", 0)

    + 0.25 * vendor_summary.get("Compliance", 0)

    + 0.15 * vendor_summary.get("Operational", 0)

)

In [49]:
vendor_summary["risk_score"] = (

    vendor_summary["risk_score"]

    /

    vendor_summary["risk_score"].max()

) * 100

vendor_summary["risk_score"] = vendor_summary["risk_score"].round(2)

In [50]:
def risk_level(score):

    if score <= 20:
        return "Safe"

    elif score <= 40:
        return "Low"

    elif score <= 60:
        return "Moderate"

    elif score <= 80:
        return "High"

    else:
        return "Critical"

vendor_summary["risk_level"] = vendor_summary["risk_score"].apply(risk_level)

In [51]:
vendor_summary = vendor_summary.sort_values(
    "risk_score",
    ascending=False
)

vendor_summary.head(37)

category,Compliance,Cybersecurity,Financial,Operational,risk_score,risk_level
vendor,,,,,,
AWS,7,61,6,54,100.00,Critical
Check Point,3,64,5,49,97.88,Critical
Google Cloud,6,41,17,53,82.51,Critical
Oracle,4,58,1,18,76.45,High
Cisco,4,56,4,13,73.77,High
CrowdStrike,7,47,1,34,72.92,High
Cloudflare,4,37,1,43,63.33,High
Microsoft Azure,3,29,1,47,55.29,Moderate
IBM Cloud,2,41,0,11,52.33,Moderate
Fortinet,2,40,4,4,50.49,Moderate
Snowflake,7,35,5,7,50.21,Moderate
Palo Alto Networks,1,32,6,16,46.97,Moderate
Deloitte,3,29,0,2,35.68,Low
EY,3,28,1,0,34.27,Low
KPMG,8,25,0,1,34.27,Low
SAP,4,24,2,3,32.30,Low
Oracle Cloud,6,15,0,26,32.16,Low
Okta,4,23,2,1,30.32,Low
Trend Micro,2,23,0,1,27.79,Low
PwC,3,22,0,1,27.36,Low
TCS,4,13,5,12,25.39,Low
Zscaler,7,13,2,10,24.96,Low
PayPal,6,13,2,8,23.41,Low
ServiceNow,4,14,4,1,21.30,Low
Visa,5,9,2,15,21.16,Low
Infosys,1,11,2,6,16.78,Safe
Workday,6,4,2,12,14.95,Safe
Mastercard,7,6,1,5,14.39,Safe
MongoDB,2,9,0,3,12.83,Safe
Databricks,3,5,2,9,12.69,Safe
Accenture,4,7,2,1,12.27,Safe
Wipro,5,4,1,8,11.99,Safe
Redis,2,8,0,3,11.71,Safe
Ping Identity,3,7,0,1,10.44,Safe
Stripe,5,2,0,2,6.63,Safe
Auth0,3,2,0,0,4.37,Safe

In [52]:
# Total number of risk events associated with each vendor
vendor_summary["risk_events_count"] = (
    vendor_summary[
        ["Cybersecurity", "Financial", "Compliance", "Operational"]
    ].sum(axis=1)
)

In [53]:
vendor_summary = vendor_summary[
    [
        "Cybersecurity",
        "Financial",
        "Compliance",
        "Operational",
        "risk_events_count",
        "risk_score",
        "risk_level"
    ]
]

vendor_summary.head()

category,Cybersecurity,Financial,Compliance,Operational,risk_events_count,risk_score,risk_level
vendor,,,,,,,
AWS,61,6,7,54,128,100.00,Critical
Check Point,64,5,3,49,121,97.88,Critical
Google Cloud,41,17,6,53,117,82.51,Critical
Oracle,58,1,4,18,81,76.45,High
Cisco,56,4,4,13,77,73.77,High

In [54]:
vendor_summary.to_csv(
    "vendor_summary.csv",
    index=True
)

from google.colab import files
# files.download("vendor_summary.csv")

In [55]:
# Rename column
vendor_summary.rename(
    columns={
        "risk_events_count": "total_risk_events"
    },
    inplace=True
)

In [56]:
vendor_summary.columns

Index(['Cybersecurity', 'Financial', 'Compliance', 'Operational',
       'total_risk_events', 'risk_score', 'risk_level'],
      dtype='object', name='category')

In [57]:
vendor_summary = vendor_summary.reset_index(drop=True)

In [58]:
vendor_summary.insert(
    0,
    "vendor_id",
    [f"VEN{str(i+1).zfill(3)}" for i in range(len(vendor_summary))]
)

In [59]:
vendor_summary.columns

Index(['vendor_id', 'Cybersecurity', 'Financial', 'Compliance', 'Operational',
       'total_risk_events', 'risk_score', 'risk_level'],
      dtype='object', name='category')

In [60]:
# Create vendor summary again
vendor_summary = master_news.groupby(
    ["vendor", "category"]
).size().unstack(fill_value=0)

In [61]:
# Total events
vendor_summary["total_risk_events"] = (
    vendor_summary[
        ["Cybersecurity", "Financial", "Compliance", "Operational"]
    ].sum(axis=1)
)

In [62]:
# Risk score
vendor_summary["risk_score"] = (
      0.40 * vendor_summary.get("Cybersecurity", 0)
    + 0.20 * vendor_summary.get("Financial", 0)
    + 0.25 * vendor_summary.get("Compliance", 0)
    + 0.15 * vendor_summary.get("Operational", 0)
)

vendor_summary["risk_score"] = (
    vendor_summary["risk_score"] /
    vendor_summary["risk_score"].max()
) * 100

vendor_summary["risk_score"] = vendor_summary["risk_score"].round(2)

In [63]:
def risk_level(score):

    if score <= 20:
        return "Safe"

    elif score <= 40:
        return "Low"

    elif score <= 60:
        return "Moderate"

    elif score <= 80:
        return "High"

    return "Critical"

vendor_summary["risk_level"] = vendor_summary["risk_score"].apply(risk_level)

In [64]:
vendor_summary = vendor_summary.reset_index()

vendor_summary.insert(
    0,
    "vendor_id",
    [f"VEN{str(i+1).zfill(3)}" for i in range(len(vendor_summary))]
)

vendor_summary = vendor_summary[
    [
        "vendor_id",
        "vendor",
        "Cybersecurity",
        "Financial",
        "Compliance",
        "Operational",
        "total_risk_events",
        "risk_score",
        "risk_level"
    ]
]

##PHASE 2

In [65]:
import pandas as pd
import random
from datetime import datetime, timedelta

In [66]:
vendor_df = pd.read_csv("vendor_summary.csv")

vendors = vendor_df["vendor"].tolist()

len(vendors)

36

In [67]:
api_catalog = [

"Authentication API",
"Authorization API",
"User API",
"Profile API",
"Customer API",
"Payment API",
"Billing API",
"Invoice API",
"Storage API",
"Search API",
"Analytics API",
"Recommendation API",
"Notification API",
"CRM API",
"Database API",
"Logging API",
"Audit API",
"Admin API",
"File Upload API",
"Email API"

]

In [68]:
business_units = [

"Identity",

"Payments",

"Finance",

"CRM",

"Analytics",

"Storage",

"DevOps",

"HR"

]

In [69]:
auth_types = [

"OAuth2",

"JWT",

"API Key",

"Basic",

"None"

]

In [70]:
http_methods = [

"GET",

"POST",

"PUT",

"DELETE"

]

In [71]:
apis = []

api_counter = 1

for vendor in vendors:

    selected_apis = random.sample(api_catalog, 15)

    for api in selected_apis:

        apis.append({

            "api_id":
            f"API{str(api_counter).zfill(4)}",

            "vendor":
            vendor,

            "api_name":
            api,

            "endpoint":
            "/api/v1/" +
            api.lower()
            .replace(" api","")
            .replace(" ","-"),

            "method":
            random.choice(http_methods),

            "owner":
            random.choice(business_units),

            "authentication":
            random.choice(auth_types),

            "tls_enabled":
            random.choice([True, False]),

            "rate_limit":
            random.choice([True, False]),

            "public_exposure":
            random.choice([True, False]),

            "last_used":
            datetime.today() -
            timedelta(days=random.randint(1,365))

        })

        api_counter += 1

In [72]:
api_inventory = pd.DataFrame(apis)

api_inventory.head()

,api_id,vendor,api_name,endpoint,method,owner,authentication,tls_enabled,rate_limit,public_exposure,last_used
0,API0001,AWS,Search API,/api/v1/search,GET,CRM,None,False,True,False,2026-05-14 05:34:27.473976
1,API0002,AWS,File Upload API,/api/v1/file-upload,GET,Identity,OAuth2,False,False,False,2025-12-18 05:34:27.474022
2,API0003,AWS,Recommendation API,/api/v1/recommendation,PUT,Analytics,OAuth2,False,False,False,2025-10-02 05:34:27.474041
3,API0004,AWS,Billing API,/api/v1/billing,POST,DevOps,None,False,True,False,2025-07-27 05:34:27.474057
4,API0005,AWS,Admin API,/api/v1/admin,DELETE,Identity,OAuth2,False,True,True,2026-06-02 05:34:27.474073

In [73]:
api_inventory.shape

(540, 11)

In [74]:
swagger_inventory = api_inventory.sample(
    frac=0.95,
    random_state=42
).copy()

swagger_inventory.shape

(513, 11)

In [75]:
gateway_logs = swagger_inventory.copy()

In [76]:
shadow_candidates = []

for i in range(20):

    shadow_candidates.append({

        "api_id": f"SHADOW{i+1:03}",

        "vendor": random.choice(vendors),

        "api_name": f"Internal API {i+1}",

        "endpoint": f"/internal/service{i+1}",

        "method": random.choice(http_methods),

        "owner": random.choice(business_units),

        "authentication": random.choice(auth_types),

        "tls_enabled": random.choice([True,False]),

        "rate_limit": random.choice([True,False]),

        "public_exposure": True,

        "last_used": datetime.today()

    })

shadow_df = pd.DataFrame(shadow_candidates)

In [77]:
shadow_df.head()

,api_id,vendor,api_name,endpoint,method,owner,authentication,tls_enabled,rate_limit,public_exposure,last_used
0,SHADOW001,Ping Identity,Internal API 1,/internal/service1,GET,Payments,JWT,True,False,True,2026-06-27 05:34:30.920107
1,SHADOW002,Oracle,Internal API 2,/internal/service2,PUT,DevOps,JWT,False,False,True,2026-06-27 05:34:30.920125
2,SHADOW003,EY,Internal API 3,/internal/service3,DELETE,Storage,JWT,True,True,True,2026-06-27 05:34:30.920135
3,SHADOW004,Stripe,Internal API 4,/internal/service4,PUT,DevOps,OAuth2,False,False,True,2026-06-27 05:34:30.920141
4,SHADOW005,SAP,Internal API 5,/internal/service5,DELETE,Finance,JWT,False,True,True,2026-06-27 05:34:30.920152

In [78]:
gateway_logs = pd.concat(

    [

        gateway_logs,

        shadow_df

    ],

    ignore_index=True

)

gateway_logs.shape

(533, 11)

In [79]:
inventory_endpoints = set(
    swagger_inventory["endpoint"]
)

gateway_logs["status"] = gateway_logs["endpoint"].apply(

    lambda x:

    "Shadow"

    if x not in inventory_endpoints

    else "Active"

)

In [80]:
gateway_logs["status"].value_counts()

status
Active    513
Shadow     20
Name: count, dtype: int64

Rule based API classification into active, deprecated, shadow or zombie

In [81]:
api_inventory["status"] = "Active"

In [82]:
len(api_inventory)

540

In [83]:
from datetime import datetime

today = datetime.today()

api_inventory.loc[

    ((today - api_inventory["last_used"]).dt.days > 180)

    &

    (api_inventory["public_exposure"] == True),

    "status"

] = "Zombie"

In [84]:
api_inventory.loc[

    ((today - api_inventory["last_used"]).dt.days > 120)

    &

    (api_inventory["public_exposure"] == False),

    "status"

] = "Deprecated"

In [85]:
api_inventory["status"].value_counts()

status
Active        198
Deprecated    190
Zombie        152
Name: count, dtype: int64

In [86]:
api_inventory["source"] = "Swagger"

In [87]:
api_inventory["status"].value_counts()

status
Active        198
Deprecated    190
Zombie        152
Name: count, dtype: int64

In [88]:
swagger_inventory = api_inventory.sample(
    frac=0.95,
    random_state=42
).copy()

swagger_inventory.shape

(513, 13)

generating 20 more random api inventory rows in gateway logs but not in the swagger inventory => to make these the shadow apis

In [89]:
gateway_logs = swagger_inventory.copy()

In [90]:
shadow_rows = []

for i in range(20):

    shadow_rows.append({

        "api_id": f"SHADOW{str(i+1).zfill(3)}",

        "vendor": random.choice(vendors),

        "api_name": f"Internal Service API {i+1}",

        "endpoint": f"/internal/service-{i+1}",

        "method": random.choice(http_methods),

        "owner": random.choice(business_units),

        "authentication": random.choice(auth_types),

        "tls_enabled": random.choice([True, False]),

        "rate_limit": random.choice([True, False]),

        "public_exposure": True,

        "last_used": datetime.today(),

        "status": "Shadow"

    })

shadow_df = pd.DataFrame(shadow_rows)

In [91]:
gateway_logs = pd.concat(

    [

        gateway_logs,

        shadow_df

    ],

    ignore_index=True

)

gateway_logs.shape

(533, 13)

In [92]:
# Keep only the first 533 rows
gateway_logs = gateway_logs.iloc[:533].copy()

gateway_logs.shape

(533, 13)

In [93]:
gateway_logs["status"].value_counts()

status
Active        193
Deprecated    175
Zombie        145
Shadow         20
Name: count, dtype: int64

api risk score

In [94]:
gateway_logs["risk_score"] = 0

In [95]:
gateway_logs.loc[
    gateway_logs["authentication"]=="None",
    "risk_score"
] += 20

In [96]:
gateway_logs.loc[
    gateway_logs["tls_enabled"]==False,
    "risk_score"
] += 30

In [97]:
gateway_logs.loc[
    gateway_logs["rate_limit"]==False,
    "risk_score"
] += 10

In [98]:
gateway_logs.loc[
    gateway_logs["public_exposure"]==True,
    "risk_score"
] += 40

In [99]:
gateway_logs["risk_score"].describe()

count    533.000000
mean      45.572233
std       26.794627
min        0.000000
25%       30.000000
50%       40.000000
75%       70.000000
max      100.000000
Name: risk_score, dtype: float64

In [100]:
gateway_logs.sort_values(
    by="risk_score",
    ascending=False
).head(20)

,api_id,vendor,api_name,endpoint,method,owner,authentication,tls_enabled,rate_limit,public_exposure,last_used,status,source,risk_score
47,API0397,Workday,Audit API,/api/v1/audit,PUT,DevOps,None,False,False,True,2026-05-27 05:34:27.479781,Active,Swagger,100
50,API0236,SAP,Storage API,/api/v1/storage,GET,Finance,None,False,False,True,2026-04-02 05:34:27.477930,Active,Swagger,100
432,API0508,Ping Identity,Authentication API,/api/v1/authentication,PUT,HR,None,False,False,True,2025-10-27 05:34:27.480647,Zombie,Swagger,100
313,API0507,Ping Identity,Payment API,/api/v1/payment,POST,Identity,None,False,False,True,2026-05-02 05:34:27.480640,Active,Swagger,100
18,API0527,Auth0,File Upload API,/api/v1/file-upload,DELETE,Payments,None,False,False,True,2025-12-29 05:34:27.480845,Active,Swagger,100
275,API0151,Snowflake,Recommendation API,/api/v1/recommendation,DELETE,Payments,None,False,False,True,2025-12-14 05:34:27.476771,Zombie,Swagger,100
236,API0110,Microsoft Azure,Search API,/api/v1/search,GET,Identity,None,False,False,True,2026-04-13 05:34:27.475987,Active,Swagger,100
283,API0434,MongoDB,CRM API,/api/v1/crm,POST,Payments,None,False,False,True,2026-06-19 05:34:27.480069,Active,Swagger,100
257,API0349,ServiceNow,Profile API,/api/v1/profile,DELETE,Identity,None,False,False,True,2026-02-23 05:34:27.479326,Active,Swagger,100
193,API0061,Cisco,Analytics API,/api/v1/analytics,DELETE,Analytics,None,False,False,True,2026-01-03 05:34:27.475271,Active,Swagger,100
195,API0111,Microsoft Azure,Invoice API,/api/v1/invoice,GET,Finance,None,False,False,True,2026-06-18 05:34:27.476001,Active,Swagger,100
210,API0115,Microsoft Azure,Logging API,/api/v1/logging,PUT,HR,None,False,False,True,2025-12-19 05:34:27.476048,Zombie,Swagger,100
78,API0210,EY,Payment API,/api/v1/payment,PUT,Analytics,None,False,True,True,2025-07-29 05:34:27.477557,Zombie,Swagger,90
318,API0394,Workday,Authentication API,/api/v1/authentication,DELETE,DevOps,None,False,True,True,2026-05-22 05:34:27.479759,Active,Swagger,90
187,API0017,Check Point,Profile API,/api/v1/profile,POST,HR,None,False,True,True,2026-04-08 05:34:27.474266,Active,Swagger,90
148,API0503,Ping Identity,CRM API,/api/v1/crm,DELETE,Storage,None,False,True,True,2025-10-26 05:34:27.480612,Zombie,Swagger,90
341,API0116,Microsoft Azure,Storage API,/api/v1/storage,DELETE,Identity,None,False,True,True,2026-03-14 05:34:27.476058,Active,Swagger,90
339,API0259,Okta,Audit API,/api/v1/audit,DELETE,Identity,None,False,True,True,2025-11-01 05:34:27.478261,Zombie,Swagger,90
246,API0104,Cloudflare,CRM API,/api/v1/crm,PUT,HR,None,False,True,True,2026-03-20 05:34:27.475901,Active,Swagger,90
330,API0152,Snowflake,Storage API,/api/v1/storage,DELETE,Finance,None,False,True,True,2025-10-06 05:34:27.476785,Zombie,Swagger,90

In [101]:
gateway_logs.loc[
    gateway_logs["status"]=="Shadow",
    "risk_score"
] += 20

gateway_logs["risk_score"] = gateway_logs["risk_score"].clip(upper=100)

In [102]:
def api_risk_level(score):

    if score <= 20:
        return "Low"

    elif score <= 50:
        return "Moderate"

    elif score <= 80:
        return "High"

    else:
        return "Critical"
gateway_logs.loc[
    gateway_logs["status"]=="Deprecated",
    "risk_score"
] += 10

gateway_logs.loc[
    gateway_logs["status"]=="Zombie",
    "risk_score"
] += 20

gateway_logs.loc[
    gateway_logs["status"]=="Shadow",
    "risk_score"
] += 30

gateway_logs["risk_score"] = gateway_logs["risk_score"].clip(upper=100)
gateway_logs["risk_level"] = gateway_logs["risk_score"].apply(api_risk_level)

In [103]:
gateway_logs["risk_level"].value_counts()

risk_level
High        163
Moderate    159
Critical    108
Low         103
Name: count, dtype: int64

In [104]:
gateway_logs.sort_values(
    by="risk_score",
    ascending=False
)[
    [
        "api_id",
        "vendor",
        "api_name",
        "status",
        "risk_score",
        "risk_level"
    ]
].head(20)

,api_id,vendor,api_name,status,risk_score,risk_level
532,SHADOW020,Databricks,Internal Service API 20,Shadow,100,Critical
531,SHADOW019,Zscaler,Internal Service API 19,Shadow,100,Critical
514,SHADOW002,SAP,Internal Service API 2,Shadow,100,Critical
24,API0480,Wipro,File Upload API,Zombie,100,Critical
26,API0181,Deloitte,File Upload API,Zombie,100,Critical
500,API0051,Oracle,Authentication API,Zombie,100,Critical
507,API0188,Deloitte,Customer API,Zombie,100,Critical
50,API0236,SAP,Storage API,Active,100,Critical
47,API0397,Workday,Audit API,Active,100,Critical
75,API0251,Oracle Cloud,Storage API,Zombie,100,Critical
69,API0133,IBM Cloud,CRM API,Zombie,100,Critical
432,API0508,Ping Identity,Authentication API,Zombie,100,Critical
92,API0278,Trend Micro,Billing API,Zombie,100,Critical
107,API0407,Mastercard,Admin API,Zombie,100,Critical
413,API0379,Infosys,Admin API,Zombie,100,Critical
78,API0210,EY,Payment API,Zombie,100,Critical
76,API0064,Cisco,Authentication API,Zombie,100,Critical
65,API0487,Redis,Payment API,Zombie,100,Critical
491,API0535,Auth0,Search API,Zombie,100,Critical
56,API0105,Cloudflare,Billing API,Zombie,100,Critical

In [105]:
api_inventory_final = gateway_logs[
    [
        "api_id",
        "vendor",
        "api_name",
        "endpoint",
        "method",
        "owner",
        "authentication",
        "tls_enabled",
        "rate_limit",
        "public_exposure",
        "last_used",
        "status",
        "risk_score",
        "risk_level"
    ]
]

In [106]:
gateway_logs.rename(
    columns={
        "owner": "business_unit"
    },
    inplace=True
)

In [107]:
gateway_logs.columns

Index(['api_id', 'vendor', 'api_name', 'endpoint', 'method', 'business_unit',
       'authentication', 'tls_enabled', 'rate_limit', 'public_exposure',
       'last_used', 'status', 'source', 'risk_score', 'risk_level'],
      dtype='object')

In [108]:
api_inventory_final = gateway_logs[
    [
        "api_id",
        "vendor",
        "api_name",
        "endpoint",
        "method",
        "business_unit",
        "authentication",
        "tls_enabled",
        "rate_limit",
        "public_exposure",
        "last_used",
        "status",
        "risk_score",
        "risk_level"
    ]
]

In [109]:
api_inventory_final.head()

,api_id,vendor,api_name,endpoint,method,business_unit,authentication,tls_enabled,rate_limit,public_exposure,last_used,status,risk_score,risk_level
0,API0230,SAP,Authentication API,/api/v1/authentication,POST,HR,JWT,False,False,True,2026-05-31 05:34:27.477850,Active,80,High
1,API0074,Cisco,Invoice API,/api/v1/invoice,PUT,DevOps,OAuth2,False,False,False,2026-05-21 05:34:27.475472,Active,40,Moderate
2,API0522,Stripe,Audit API,/api/v1/audit,GET,Analytics,JWT,True,False,True,2026-04-01 05:34:27.480801,Active,50,Moderate
3,API0087,CrowdStrike,Profile API,/api/v1/profile,DELETE,Analytics,API Key,True,True,False,2026-05-11 05:34:27.475688,Active,0,Low
4,API0470,Wipro,Payment API,/api/v1/payment,POST,Identity,JWT,False,False,False,2025-10-20 05:34:27.480352,Deprecated,50,Moderate

In [110]:
api_inventory_final.to_csv(
    "api_inventory.csv",
    index=False
)

In [111]:
from google.colab import files

# files.download("api_inventory.csv")

In [112]:
vendor_summary.head()

category,vendor_id,vendor,Cybersecurity,Financial,Compliance,Operational,total_risk_events,risk_score,risk_level
0,VEN001,AWS,61,6,7,54,128,100.00,Critical
1,VEN002,Accenture,7,2,4,1,14,12.27,Safe
2,VEN003,Auth0,2,0,3,0,5,4.37,Safe
3,VEN004,Check Point,64,5,3,49,121,97.88,Critical
4,VEN005,Cisco,56,4,4,13,77,73.77,High

In [113]:
vendor_summary = pd.read_csv(
    "vendor_summary.csv"
)

api_inventory = pd.read_csv(
    "api_inventory.csv"
)

In [114]:
print(vendor_summary.shape)
print(api_inventory.shape)

display(vendor_summary.head())
display(api_inventory.head())

(36, 8)
(533, 14)

,vendor,Cybersecurity,Financial,Compliance,Operational,risk_events_count,risk_score,risk_level
0,AWS,61,6,7,54,128,100.00,Critical
1,Check Point,64,5,3,49,121,97.88,Critical
2,Google Cloud,41,17,6,53,117,82.51,Critical
3,Oracle,58,1,4,18,81,76.45,High
4,Cisco,56,4,4,13,77,73.77,High

,api_id,vendor,api_name,endpoint,method,business_unit,authentication,tls_enabled,rate_limit,public_exposure,last_used,status,risk_score,risk_level
0,API0230,SAP,Authentication API,/api/v1/authentication,POST,HR,JWT,False,False,True,2026-05-31 05:34:27.477850,Active,80,High
1,API0074,Cisco,Invoice API,/api/v1/invoice,PUT,DevOps,OAuth2,False,False,False,2026-05-21 05:34:27.475472,Active,40,Moderate
2,API0522,Stripe,Audit API,/api/v1/audit,GET,Analytics,JWT,True,False,True,2026-04-01 05:34:27.480801,Active,50,Moderate
3,API0087,CrowdStrike,Profile API,/api/v1/profile,DELETE,Analytics,API Key,True,True,False,2026-05-11 05:34:27.475688,Active,0,Low
4,API0470,Wipro,Payment API,/api/v1/payment,POST,Identity,JWT,False,False,False,2025-10-20 05:34:27.480352,Deprecated,50,Moderate

In [115]:
import pandas as pd
cyber_news = pd.read_csv("cyber_news.csv")
master_news = pd.read_csv("master_news.csv")
vendor_summary = pd.read_csv("vendor_summary.csv")
api_inventory = pd.read_csv("api_inventory.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'cyber_news.csv'

In [116]:
print(vendor_summary.shape)
print(api_inventory.shape)

display(vendor_summary.head())
display(api_inventory.head())

(36, 8)
(533, 14)

,vendor,Cybersecurity,Financial,Compliance,Operational,risk_events_count,risk_score,risk_level
0,AWS,61,6,7,54,128,100.00,Critical
1,Check Point,64,5,3,49,121,97.88,Critical
2,Google Cloud,41,17,6,53,117,82.51,Critical
3,Oracle,58,1,4,18,81,76.45,High
4,Cisco,56,4,4,13,77,73.77,High

,api_id,vendor,api_name,endpoint,method,business_unit,authentication,tls_enabled,rate_limit,public_exposure,last_used,status,risk_score,risk_level
0,API0230,SAP,Authentication API,/api/v1/authentication,POST,HR,JWT,False,False,True,2026-05-31 05:34:27.477850,Active,80,High
1,API0074,Cisco,Invoice API,/api/v1/invoice,PUT,DevOps,OAuth2,False,False,False,2026-05-21 05:34:27.475472,Active,40,Moderate
2,API0522,Stripe,Audit API,/api/v1/audit,GET,Analytics,JWT,True,False,True,2026-04-01 05:34:27.480801,Active,50,Moderate
3,API0087,CrowdStrike,Profile API,/api/v1/profile,DELETE,Analytics,API Key,True,True,False,2026-05-11 05:34:27.475688,Active,0,Low
4,API0470,Wipro,Payment API,/api/v1/payment,POST,Identity,JWT,False,False,False,2025-10-20 05:34:27.480352,Deprecated,50,Moderate

In [117]:
application_catalog = [

    "Payment Service",

    "Billing Service",

    "Identity Service",

    "Analytics Platform",

    "CRM Service",

    "Storage Platform",

    "Notification Service",

    "Customer Portal",

    "Finance Portal",

    "HR Portal",

    "Search Platform",

    "Admin Portal"

]

In [118]:
applications = []

app_counter = 1

for vendor in vendor_summary["vendor"]:

    selected_apps = random.sample(
        application_catalog,
        3
    )

    for app in selected_apps:

        applications.append({

            "app_id":
            f"APP{str(app_counter).zfill(3)}",

            "vendor":
            vendor,

            "application":
            app

        })

        app_counter += 1

applications_df = pd.DataFrame(
    applications
)

applications_df.head(10)

   app_id        vendor       application
0  APP001           AWS         HR Portal
1  APP002           AWS    Finance Portal
2  APP003           AWS       CRM Service
3  APP004   Check Point      Admin Portal
4  APP005   Check Point   Billing Service
5  APP006   Check Point         HR Portal
6  APP007  Google Cloud   Customer Portal
7  APP008  Google Cloud   Search Platform
8  APP009  Google Cloud  Identity Service
9  APP010        Oracle      Admin Portal

In [119]:
applications_df = applications_df.merge(

    vendor_summary[
        [
            "vendor",
            "risk_score"
        ]
    ],

    on="vendor",

    how="left"

)

In [120]:
applications_df.rename(

    columns={

        "risk_score":
        "base_risk"

    },

    inplace=True

)

In [121]:
applications_df.head()

   app_id       vendor      application  base_risk
0  APP001          AWS        HR Portal     100.00
1  APP002          AWS   Finance Portal     100.00
2  APP003          AWS      CRM Service     100.00
3  APP004  Check Point     Admin Portal      97.88
4  APP005  Check Point  Billing Service      97.88

application -> api mapping

In [122]:
api_inventory["app_id"] = None

In [123]:
import numpy as np
for vendor in vendor_summary["vendor"]:

    vendor_apps = applications_df[
        applications_df["vendor"] == vendor
    ]["app_id"].tolist()

    vendor_api_idx = api_inventory[
        api_inventory["vendor"] == vendor
    ].index

    assigned_apps = np.random.choice(
        vendor_apps,
        size=len(vendor_api_idx),
        replace=True
    )

    api_inventory.loc[
        vendor_api_idx,
        "app_id"
    ] = assigned_apps

In [124]:
api_inventory[
    [
        "vendor",
        "app_id",
        "api_name"
    ]
].head(20)

             vendor  app_id            api_name
0               SAP  APP048  Authentication API
1             Cisco  APP015         Invoice API
2            Stripe  APP103           Audit API
3       CrowdStrike  APP016         Profile API
4             Wipro  APP095         Payment API
5       CrowdStrike  APP017   Authorization API
6               PwC  APP060     File Upload API
7        Mastercard  APP082           Audit API
8            PayPal  APP067         Invoice API
9           Infosys  APP078         Storage API
10              AWS  APP001         Payment API
11  Microsoft Azure  APP022         Profile API
12       Mastercard  APP083            User API
13      CrowdStrike  APP016  Authentication API
14      Trend Micro  APP056         Payment API
15               EY  APP042        Customer API
16            Redis  APP097           Email API
17       Cloudflare  APP019           Audit API
18            Auth0  APP107     File Upload API
19           Oracle  APP011             CRM API

In [125]:
api_inventory = api_inventory.merge(

    applications_df[
        [
            "app_id",
            "application"
        ]
    ],

    on="app_id",

    how="left"

)

In [126]:
api_inventory[
    [
        "vendor",
        "application",
        "api_name",
        "business_unit"
    ]
].head()

        vendor           application            api_name business_unit
0          SAP        Finance Portal  Authentication API            HR
1        Cisco  Notification Service         Invoice API        DevOps
2       Stripe  Notification Service           Audit API     Analytics
3  CrowdStrike    Analytics Platform         Profile API     Analytics
4        Wipro       Billing Service         Payment API      Identity

#PHASE 3: enterprise graph building

In [127]:
import networkx as nx
import matplotlib.pyplot as plt
G = nx.DiGraph()

In [128]:
for _, row in vendor_summary.iterrows():

    G.add_node(
        row["vendor"],
        node_type="Vendor",
        base_risk=row["risk_score"]
    )

In [129]:
for _, row in applications_df.iterrows():

    G.add_node(
        row["app_id"],
        node_type="Application",
        base_risk=row["base_risk"]
    )

    G.add_edge(
        row["vendor"],
        row["app_id"],
        weight=0.8
    )

In [130]:
for _, row in api_inventory.iterrows():

    G.add_node(
        row["api_id"],
        node_type="API",
        base_risk=row["risk_score"]
    )

    G.add_edge(
        row["app_id"],
        row["api_id"],
        weight=0.6
    )

In [131]:
business_units = api_inventory[
    "business_unit"
].unique()

In [132]:
for bu in business_units:

    G.add_node(
        bu,
        node_type="BusinessUnit",
        base_risk=30
    )

In [133]:
for _, row in api_inventory.iterrows():

    G.add_edge(
        row["api_id"],
        row["business_unit"],
        weight=0.4
    )

In [134]:
print(
    "Nodes:",
    G.number_of_nodes()
)

print(
    "Edges:",
    G.number_of_edges()
)

Nodes: 685
Edges: 1174

risk propagation engine - prop function

In [135]:
def propagate_risk(
    graph,
    alpha=0.3
):

    propagated = {}

    for node in graph.nodes():

        base_risk = graph.nodes[node].get(
            "base_risk",
            0
        )

        incoming_risk = 0

        for parent in graph.predecessors(node):

            weight = graph[
                parent
            ][node]["weight"]

            parent_risk = graph.nodes[
                parent
            ].get(
                "base_risk",
                0
            )

            incoming_risk += (
                weight *
                parent_risk
            )

        propagated_risk = (

            base_risk

            +

            alpha *
            incoming_risk

        )

        propagated[node] = min(
            100,
            round(
                propagated_risk,
                2
            )
        )

    return propagated

In [136]:
propagated_risks = propagate_risk(
    G
)

In [137]:
nx.set_node_attributes(

    G,

    propagated_risks,

    "propagated_risk"

)

In [138]:
risk_df = pd.DataFrame({

    "node":

    list(
        propagated_risks.keys()
    ),

    "propagated_risk":

    list(
        propagated_risks.values()
    )

})

In [139]:
risk_df.sort_values(

    by="propagated_risk",

    ascending=False

).head(20)

          node  propagated_risk
684    Finance            100.0
0          AWS            100.0
683    Storage            100.0
682   Payments            100.0
680   Identity            100.0
681        CRM            100.0
679  Analytics            100.0
663  SHADOW007            100.0
644    API0051            100.0
662  SHADOW006            100.0
661  SHADOW005            100.0
660  SHADOW004            100.0
659  SHADOW003            100.0
658  SHADOW002            100.0
651    API0188            100.0
39      APP004            100.0
628    API0014            100.0
38      APP003            100.0
37      APP002            100.0
36      APP001            100.0

enterprise risk scores:

In [140]:
vendor_nodes = [

    n

    for n,d

    in G.nodes(data=True)

    if d["node_type"]=="Vendor"

]

In [141]:
application_nodes = [

    n

    for n,d

    in G.nodes(data=True)

    if d["node_type"]=="Application"

]

In [142]:
api_nodes = [

    n

    for n,d

    in G.nodes(data=True)

    if d["node_type"]=="API"

]

In [143]:
bu_nodes = [

    n

    for n,d

    in G.nodes(data=True)

    if d["node_type"]=="BusinessUnit"

]

In [144]:
vendor_avg = np.mean(

    [
        propagated_risks[n]

        for n in vendor_nodes
    ]

)

In [145]:
application_avg = np.mean(

    [
        propagated_risks[n]

        for n in application_nodes
    ]

)

In [146]:
api_avg = np.mean(

    [
        propagated_risks[n]

        for n in api_nodes
    ]

)

In [147]:
bu_avg = np.mean(

    [
        propagated_risks[n]

        for n in bu_nodes
    ]

)

In [148]:
enterprise_risk_score = (

      0.4 * vendor_avg

    + 0.3 * application_avg

    + 0.2 * api_avg

    + 0.1 * bu_avg

)

In [149]:
enterprise_risk_score = round(
    enterprise_risk_score,
    2
)
print(
    "Enterprise Risk Score:",
    enterprise_risk_score
)

Enterprise Risk Score: 50.15

In [150]:
def enterprise_level(score):

    if score <= 20:
        return "Safe"

    elif score <= 40:
        return "Low"

    elif score <= 60:
        return "Moderate"

    elif score <= 80:
        return "High"

    return "Critical"

In [151]:
enterprise_risk_level = enterprise_level(
    enterprise_risk_score
)

In [152]:
print(enterprise_risk_level)

Moderate

In [153]:
applications_df.to_csv(
    "enterprise_applications.csv",
    index=False
)

In [154]:
edges_df = pd.DataFrame(

    [

        (

            u,

            v,

            d["weight"]

        )

        for u,v,d

        in G.edges(data=True)

    ],

    columns=[
        "source",
        "target",
        "weight"
    ]

)

In [155]:
edges_df.to_csv(
    "enterprise_graph.csv",
    index=False
)

In [156]:
risk_df.to_csv(
    "enterprise_risk.csv",
    index=False
)

In [157]:
from google.colab import files

# files.download("enterprise_applications.csv")
# files.download("enterprise_graph.csv")
# files.download("enterprise_risk.csv")

#PHASE 4

In [158]:
!pip -q install langchain
!pip -q install langchain-community
!pip -q install langchain-google-genai
!pip -q install faiss-cpu
!pip -q install sentence-transformers
!pip -q install pypdf

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 39.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 31.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.5/70.5 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 54.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.5/349.5 kB 9.5 MB/s eta 0:00:00

In [159]:
!pip install -qU langchain
!pip install -qU langchain-community
!pip install -qU langchain-core
!pip install -qU langchain-google-genai
!pip install -qU faiss-cpu
!pip install -qU sentence-transformers
!pip install -qU google-generativeai

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.4/557.4 kB 15.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.4/596.4 kB 11.8 MB/s eta 0:00:00

In [160]:
!pip install -q faiss-cpu
!pip install -q sentence-transformers
!pip install -q google-generativeai
!pip install -q langchain

In [161]:
import os
import faiss
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer

import google.generativeai as genai

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

In [162]:
import pandas as pd

vendor_df = pd.read_csv("vendor_summary.csv")
news_df = pd.read_csv("master_news.csv")
api_df = pd.read_csv("api_inventory.csv")
applications_df = pd.read_csv("enterprise_applications.csv")
graph_df = pd.read_csv("enterprise_graph.csv")
risk_df = pd.read_csv("enterprise_risk.csv")

In [163]:
print("Vendor:", vendor_df.shape)
print("News:", news_df.shape)
print("API:", api_df.shape)
print("Applications:", applications_df.shape)
print("Graph:", graph_df.shape)
print("Risk:", risk_df.shape)

Vendor: (36, 8)
News: (1568, 13)
API: (533, 14)
Applications: (108, 4)
Graph: (1174, 3)
Risk: (685, 2)

In [164]:
knowledge_base = []

In [165]:
for _, row in vendor_df.iterrows():

    knowledge_base.append(
        f"""
Vendor Name: {row['vendor']}
Vendor Risk Score: {row['risk_score']}
Vendor Risk Level: {row['risk_level']}
Cybersecurity Incidents: {row['Cybersecurity']}
Financial Events: {row['Financial']}
Compliance Events: {row['Compliance']}
Operational Events: {row['Operational']}
"""
    )

In [166]:
for _, row in api_df.iterrows():

    knowledge_base.append(
        f"""
Vendor: {row['vendor']}
API Name: {row['api_name']}
API Status: {row['status']}
API Risk Score: {row['risk_score']}
Risk Level: {row['risk_level']}
Business Unit: {row['business_unit']}
Authentication: {row['authentication']}
TLS Enabled: {row['tls_enabled']}
Rate Limited: {row['rate_limit']}
Public Exposure: {row['public_exposure']}
"""
    )

In [167]:
for _, row in news_df.iterrows():

    knowledge_base.append(
        f"""
Vendor: {row['vendor']}
Category: {row['category']}
Headline:
{row['title']}
"""
    )

In [168]:
for _, row in risk_df.iterrows():

    knowledge_base.append(
        f"""
Enterprise Node: {row['node']}
Propagated Risk: {row['propagated_risk']}
"""
    )

In [169]:
print(len(knowledge_base))

2822

creating embeddings:

In [170]:
from sentence_transformers import SentenceTransformer

In [171]:
embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [172]:
embeddings = embedding_model.encode(
    knowledge_base,
    show_progress_bar=True
)

Batches:   0%|          | 0/89 [00:00<?, ?it/s]

In [173]:
embeddings.shape

(2822, 384)

faiss indexing:

In [174]:
import faiss
import numpy as np

In [175]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(
    np.array(embeddings).astype("float32")
)

In [176]:
index.ntotal

2822

rag search function (retrieval):

In [177]:
def retrieve(query, k=5):

    query_embedding = embedding_model.encode([query])

    distances, indices = index.search(
        np.array(query_embedding).astype("float32"),
        k
    )

    docs = []

    for idx in indices[0]:
        docs.append(
            knowledge_base[idx]
        )

    return docs

In [178]:
# TEST1
results = retrieve(
    "Why is Oracle high risk?"
)

for i, doc in enumerate(results):

    print("="*60)

    print(f"Document {i+1}")

    print(doc)

============================================================
Document 1

Enterprise Node: Oracle
Propagated Risk: 76.45

============================================================
Document 2

Enterprise Node: Oracle Cloud
Propagated Risk: 32.16

============================================================
Document 3

Vendor Name: Oracle
Vendor Risk Score: 76.45
Vendor Risk Level: High
Cybersecurity Incidents: 58
Financial Events: 1
Compliance Events: 4
Operational Events: 18

============================================================
Document 4

Vendor: Oracle
Category: Cybersecurity
Headline:
CFOs and Cybersecurity: Top Threats and How to Prevent Them - Oracle

============================================================
Document 5

Vendor: Oracle
Category: Cybersecurity
Headline:
Introducing DBSAT 3.1 integration with Enterprise Manager: automated database risk and security assessment - Oracle Blogs

In [179]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
import shutil

files_to_save = [
    "vendor_summary.csv",
    "master_news.csv",
    "api_inventory.csv",
    "enterprise_applications.csv",
    "enterprise_graph.csv",
    "enterprise_risk.csv"
]

for f in files_to_save:
    try:
        shutil.copy(f, "/content/drive/MyDrive/")
        print(f"Saved: {f}")
    except:
        print(f"Missing: {f}")

google api

In [180]:
import google.generativeai as genai

In [ ]:
GOOGLE_API_KEY = "AIzaSyAbapZLindmgLUI3IAICn5XBamhR1mOM5k"
genai.configure(
    api_key=GOOGLE_API_KEY
)

In [182]:
!pip show google-generativeai


import google.generativeai as genai

print(genai.__version__)

Name: google-generativeai
Version: 0.8.6
Summary: Google Generative AI High level API client library and tools.
Home-page: https://github.com/google/generative-ai-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: google-ai-generativelanguage, google-api-core, google-api-python-client, google-auth, protobuf, pydantic, tqdm, typing-extensions
Required-by:
0.8.6

In [183]:
model = genai.GenerativeModel(
    "gemini-2.5-flash"
)

In [184]:
# def enterprise_ai(question):

#     retrieved_docs = retrieve(question, k=5)

#     context = "\n\n".join(retrieved_docs)

#     prompt = f"""
# You are an Enterprise Risk AI Analyst.

# Use ONLY the information provided below.

# Do not hallucinate.

# If the answer cannot be found, explicitly state that.

# Enterprise Knowledge:

# {context}

# Question:

# {question}

# Answer professionally.

# Also provide recommendations whenever possible.
# """

#     response = model.generate_content(prompt)

#     return response.text

In [185]:
#test2:
print(
    enterprise_ai(
        "Why is Oracle High Risk?"
    )
)

NameError: name 'enterprise_ai' is not defined

In [186]:
graph_df = pd.read_csv("enterprise_graph.csv")

graph_df.head()

        source  target  weight
0          AWS  APP001     0.8
1          AWS  APP002     0.8
2          AWS  APP003     0.8
3  Check Point  APP004     0.8
4  Check Point  APP005     0.8

In [187]:
import networkx as nx

enterprise_graph = nx.DiGraph()

for _, row in graph_df.iterrows():

    enterprise_graph.add_edge(

        row["source"],

        row["target"],

        weight=row["weight"]

    )

In [188]:
print(

    enterprise_graph.number_of_nodes(),

    enterprise_graph.number_of_edges()

)

685 1174

In [189]:
vendors = vendor_df["vendor"].tolist()

In [190]:
def extract_vendor(question):

    question = question.lower()

    for vendor in vendors:

        if vendor.lower() in question:

            return vendor

    return None

In [191]:
extract_vendor(

    "Why is Oracle High Risk?"

)

'Oracle'

In [192]:
def get_enterprise_context(vendor):

    context = {}

    apps = list(

        enterprise_graph.successors(

            vendor

        )

    )

    context["applications"] = apps

    apis = []

    business_units = []

    for app in apps:

        app_apis = list(

            enterprise_graph.successors(

                app

            )

        )

        apis.extend(app_apis)

        for api in app_apis:

            bus = list(

                enterprise_graph.successors(

                    api

                )

            )

            business_units.extend(bus)

    context["apis"] = list(

        set(apis)

    )

    context["business_units"] = list(

        set(business_units)

    )

    return context

In [193]:
get_enterprise_context("Oracle")

{'applications': ['APP010', 'APP011', 'APP012'],
 'apis': ['API0049',
  'API0056',
  'API0055',
  'API0060',
  'API0054',
  'API0052',
  'API0050',
  'API0051',
  'API0059',
  'API0053',
  'API0046',
  'API0057',
  'API0058',
  'API0047',
  'API0048'],
 'business_units': ['DevOps',
  'Identity',
  'Analytics',
  'HR',
  'Payments',
  'Finance',
  'CRM']}

In [194]:
def build_context(question):

    vendor = extract_vendor(question)

    rag_docs = retrieve(question, k=5)

    graph_context = ""

    if vendor is not None:

        graph_data = get_enterprise_context(vendor)

        graph_context += f"""

Vendor:

{vendor}

Connected Applications:

{', '.join(graph_data['applications'])}

Connected APIs:

{', '.join(graph_data['apis'])}

Affected Business Units:

{', '.join(graph_data['business_units'])}

"""

    return graph_context + "\n\n".join(rag_docs)

In [195]:
print(

    build_context(

        "Why is Oracle High Risk?"

    )

)

Vendor:

Oracle

Connected Applications:

APP010, APP011, APP012

Connected APIs:

API0049, API0056, API0055, API0060, API0054, API0052, API0050, API0051, API0059, API0053, API0046, API0057, API0058, API0047, API0048

Affected Business Units:

DevOps, Identity, Analytics, HR, Payments, Finance, CRM


Enterprise Node: Oracle
Propagated Risk: 76.45



Enterprise Node: Oracle Cloud
Propagated Risk: 32.16



Vendor Name: Oracle
Vendor Risk Score: 76.45
Vendor Risk Level: High
Cybersecurity Incidents: 58
Financial Events: 1
Compliance Events: 4
Operational Events: 18



Vendor: Oracle
Category: Cybersecurity
Headline:
CFOs and Cybersecurity: Top Threats and How to Prevent Them - Oracle



Vendor: Oracle
Category: Cybersecurity
Headline:
Introducing DBSAT 3.1 integration with Enterprise Manager: automated database risk and security assessment - Oracle Blogs

In [196]:
def enterprise_ai(question):

    context = build_context(question)

    prompt = f"""
You are an Enterprise Risk Intelligence Analyst.

Use ONLY the enterprise knowledge provided.

Your answer must contain:

1. Executive Summary

2. Root Cause Analysis

3. Risk Propagation

4. Impacted Applications

5. Impacted APIs

6. Impacted Business Units

7. Recommended Mitigations

Enterprise Knowledge

{context}

Question

{question}

Return a professional cybersecurity report.
"""

    response = model.generate_content(prompt)

    return response.text

In [197]:
print(

enterprise_ai(

"Why is Oracle High Risk?"

)

)

**Enterprise Risk Intelligence Report: Oracle Vendor Risk Assessment**

**Date:** October 26, 2023
**Prepared For:** Enterprise Leadership Team
**Subject:** Analysis of Oracle's High-Risk Classification

---

### 1. Executive Summary

This report provides an analysis of why Oracle has been classified as a **High Risk** vendor to our enterprise, evidenced by a Vendor Risk Score of **76.45**. The primary drivers for this elevated risk include a significant number of reported cybersecurity incidents (58), alongside operational, compliance, and financial events. This high-risk posture results in a substantial propagated risk throughout our interconnected systems and business units, impacting critical applications, APIs, and key operational areas such as Finance, HR, and Payments. Immediate mitigation strategies are recommended to address the identified vulnerabilities and enhance our overall security posture.

---

### 2. Root Cause Analysis

Oracle's classification as a High Risk vendor is primarily attributed to the following factors:

*   **High Vendor Risk Score:** Oracle has an assessed Vendor Risk Score of **76.45**, placing it squarely in the "High" risk category.
*   **Significant Cybersecurity Incidents:** The most prominent contributor to this high score is the documented **58 cybersecurity incidents** associated with Oracle. This indicates a consistent or severe exposure to cyber threats, either within Oracle's own infrastructure or its products, which directly impacts the security assurance of our systems relying on Oracle.
*   **Operational Events:** A substantial **18 operational events** further contribute to the risk, suggesting potential instability or reliability concerns that could disrupt business processes dependent on Oracle services.
*   **Compliance and Financial Events:** While fewer in number, **4 compliance events** and **1 financial event** indicate additional areas of concern that could lead to regulatory penalties or financial instability, indirectly affecting service delivery or data integrity.
*   **Known Cybersecurity Focus:** Oracle's own communications, such as "CFOs and Cybersecurity: Top Threats and How to Prevent Them" and "Introducing DBSAT 3.1 integration with Enterprise Manager: automated database risk and security assessment," highlight an ongoing and critical focus on cybersecurity threats and database security. While these initiatives aim to improve security, the sheer volume of incidents observed suggests persistent challenges that translate into enterprise risk.

---

### 3. Risk Propagation

The high risk associated with Oracle propagates significantly across our enterprise infrastructure:

*   **Oracle Enterprise Node:** The "Oracle" enterprise node itself carries a **Propagated Risk of 76.45**, mirroring its vendor risk score. This indicates that the inherent risks from Oracle's operations, security posture, and incidents are directly reflected in the overall risk profile of systems and services deeply integrated with Oracle.
*   **Oracle Cloud Enterprise Node:** Even services hosted on "Oracle Cloud" contribute to enterprise risk, showing a **Propagated Risk of 32.16**. While lower than the core Oracle node, this still represents a notable risk vector, suggesting that even cloud-based deployments require careful scrutiny.
*   **Interconnectedness:** Due to the extensive connectivity of Oracle products and services to our internal applications, APIs, and business processes, any compromise or operational issue stemming from Oracle can cascade rapidly, affecting critical business functions and data integrity across the organization.

---

### 4. Impacted Applications

Should a significant incident occur related to Oracle's high-risk status, the following critical applications are directly exposed:

*   APP010
*   APP011
*   APP012

---

### 5. Impacted APIs

A wide array of enterprise APIs relies on Oracle, making them susceptible to propagated risks:

*   API0049
*   API0056
*   API0055
*   API0060
*   API0054
*   API0052
*   API0050
*   API0051
*   API0059
*   API0053
*   API0046
*   API0057
*   API0058
*   API0047
*   API0048

---

### 6. Impacted Business Units

The high risk associated with Oracle has a direct potential impact on several key business units, indicating broad operational and financial exposure:

*   DevOps
*   Identity
*   Analytics
*   HR
*   Payments
*   Finance
*   CRM

---

### 7. Recommended Mitigations

To address the high risk posed by Oracle, the following mitigation strategies are recommended:

*   **Enhanced Security Monitoring:** Implement robust, real-time security monitoring specifically for all systems and applications connected to Oracle, including network traffic, database activity, and application logs.
*   **Comprehensive Vulnerability Assessments & Penetration Testing:** Conduct frequent and thorough vulnerability assessments and penetration tests on all applications (APP010, APP011, APP012) and APIs directly or indirectly relying on Oracle services.
*   **Strengthened Access Controls:** Review and reinforce least privilege access controls for all user accounts and service accounts interacting with Oracle systems, particularly for sensitive business units like Payments, Finance, and HR.
*   **Dedicated Patch Management Program:** Establish an accelerated and rigorous patch management program for all Oracle products and connected applications to ensure critical security updates are applied promptly.
*   **Vendor Risk Management Review:** Initiate an in-depth review of our contractual agreements with Oracle, focusing on security clauses, service level agreements (SLAs) for incident response, and audit rights. Engage Oracle directly to understand the root causes and mitigation plans for the 58 cybersecurity incidents.
*   **Incident Response Planning (Oracle-Specific):** Develop and test specific incident response playbooks for scenarios involving a compromise or outage of Oracle services, detailing steps for impacted applications and business units.
*   **Data Redundancy and Backup Strategy:** Ensure robust data backup and recovery mechanisms are in place for all data residing in or processed by Oracle systems, including off-site storage and immutable backups.
*   **Explore Alternative Solutions (Strategic):** For systems where Oracle is critical and the risk is consistently high, explore long-term strategic alternatives or diversification of vendors to reduce single-vendor dependency.
*   **Cloud Security Posture Management (CSPM):** For Oracle Cloud services (Propagated Risk: 32.16), implement dedicated CSPM tools and practices to continuously monitor configurations, compliance, and potential vulnerabilities.

solving api id problem in the result: gemini doesnt know what api047 or api007 stands for

In [198]:
app_lookup = dict(
    zip(
        applications_df["app_id"],
        applications_df["application"]
    )
)

api_lookup = dict(
    zip(
        api_df["api_id"],
        api_df["api_name"]
    )
)

In [199]:
def resolve_graph_context(graph_context):

    resolved_apps = []

    for app in graph_context["applications"]:

        resolved_apps.append(

            app_lookup.get(
                app,
                app
            )

        )

    resolved_apis = []

    for api in graph_context["apis"]:

        resolved_apis.append(

            api_lookup.get(
                api,
                api
            )

        )

    return {

        "applications": resolved_apps,

        "apis": resolved_apis,

        "business_units": graph_context["business_units"]

    }

In [200]:
def build_context(question):

    vendor = extract_vendor(question)

    rag_docs = retrieve(question, k=5)

    graph_text = ""

    if vendor:

        graph = get_enterprise_context(vendor)

        graph = resolve_graph_context(graph)

        graph_text = f"""

Vendor:
{vendor}

Connected Applications:
{', '.join(graph['applications'])}

Connected APIs:
{', '.join(graph['apis'])}

Affected Business Units:
{', '.join(graph['business_units'])}

"""

    return graph_text + "\n\n".join(rag_docs)

In [201]:
risk_lookup = {}

# ---------------- Vendor Risks ----------------

for _, row in vendor_df.iterrows():
    risk_lookup[row["vendor"]] = row["risk_score"]

# ---------------- Application Risks ----------------

for _, row in applications_df.iterrows():

    app_id = row["app_id"]
    app_name = row["application"]

    match = risk_df[risk_df["node"] == app_id]

    if not match.empty:
        risk_lookup[app_name] = float(match.iloc[0]["propagated_risk"])

# ---------------- API Risks ----------------

for _, row in api_df.iterrows():

    api_id = row["api_id"]
    api_name = row["api_name"]

    match = risk_df[risk_df["node"] == api_id]

    if not match.empty:
        risk_lookup[api_name] = float(match.iloc[0]["propagated_risk"])

# ---------------- Business Unit Risks ----------------

for _, row in risk_df.iterrows():

    if row["node"] in api_df["business_unit"].unique():

        risk_lookup[row["node"]] = float(row["propagated_risk"])

In [202]:
def dependency_chain(vendor):

    chain = []

    apps = list(enterprise_graph.successors(vendor))

    for app in apps:

        app_name = app_lookup.get(app, app)

        apis = list(enterprise_graph.successors(app))

        for api in apis:

            api_name = api_lookup.get(api, api)

            bus = list(enterprise_graph.successors(api))

            if len(bus):

                for bu in bus:

                    chain.append({

                        "application": app_name,

                        "api": api_name,

                        "business_unit": bu

                    })

            else:

                chain.append({

                    "application": app_name,

                    "api": api_name,

                    "business_unit": "Unknown"

                })

    return chain

In [203]:
dependency_chain("Oracle")

[{'application': 'Admin Portal',
  'api': 'Authorization API',
  'business_unit': 'HR'},
 {'application': 'Admin Portal',
  'api': 'Billing API',
  'business_unit': 'Finance'},
 {'application': 'Admin Portal',
  'api': 'File Upload API',
  'business_unit': 'DevOps'},
 {'application': 'Admin Portal',
  'api': 'Analytics API',
  'business_unit': 'Analytics'},
 {'application': 'Admin Portal',
  'api': 'Email API',
  'business_unit': 'Finance'},
 {'application': 'Admin Portal',
  'api': 'Customer API',
  'business_unit': 'Identity'},
 {'application': 'Storage Platform',
  'api': 'CRM API',
  'business_unit': 'Payments'},
 {'application': 'Storage Platform',
  'api': 'Audit API',
  'business_unit': 'Payments'},
 {'application': 'Storage Platform',
  'api': 'Search API',
  'business_unit': 'Analytics'},
 {'application': 'Storage Platform', 'api': 'User API', 'business_unit': 'HR'},
 {'application': 'Search Platform',
  'api': 'Database API',
  'business_unit': 'HR'},
 {'application': 'Search Platform',
  'api': 'Payment API',
  'business_unit': 'CRM'},
 {'application': 'Search Platform',
  'api': 'Admin API',
  'business_unit': 'Payments'},
 {'application': 'Search Platform',
  'api': 'Storage API',
  'business_unit': 'Payments'},
 {'application': 'Search Platform',
  'api': 'Authentication API',
  'business_unit': 'Analytics'}]

In [204]:
def build_graph_summary(vendor):

    graph = resolve_graph_context(
        get_enterprise_context(vendor)
    )

    dependency = dependency_chain(vendor)

    text = []

    text.append("========== ENTERPRISE GRAPH ==========\n")

    text.append(f"Vendor : {vendor}")

    text.append(
        f"Vendor Risk : {risk_lookup.get(vendor,'Unknown')}"
    )

    text.append("\nApplications")

    for app in graph["applications"]:

        text.append(
            f"• {app} | Risk {risk_lookup.get(app,'Unknown')}"
        )

    text.append("\nAPIs")

    for api in graph["apis"]:

        text.append(
            f"• {api} | Risk {risk_lookup.get(api,'Unknown')}"
        )

    text.append("\nBusiness Units")

    for bu in graph["business_units"]:

        text.append(
            f"• {bu} | Risk {risk_lookup.get(bu,'Unknown')}"
        )

    text.append("\nDependency Chains")

    for d in dependency:

        text.append(

            f"{vendor}"

            f" → "

            f"{d['application']}"

            f" → "

            f"{d['api']}"

            f" → "

            f"{d['business_unit']}"

        )

    return "\n".join(text)

In [205]:
print(

build_graph_summary(

"Oracle"

)

)

========== ENTERPRISE GRAPH ==========

Vendor : Oracle
Vendor Risk : 76.45

Applications
• Admin Portal | Risk 5.42
• Storage Platform | Risk 8.22
• Search Platform | Risk 14.87

APIs
• Admin API | Risk 80.79
• CRM API | Risk 71.19
• User API | Risk 92.16
• Billing API | Risk 41.88
• File Upload API | Risk 28.45
• Storage API | Risk 40.79
• Analytics API | Risk 79.42
• Authentication API | Risk 100.0
• Customer API | Risk 23.76
• Email API | Risk 72.28
• Audit API | Risk 72.21
• Payment API | Risk 100.0
• Authorization API | Risk 85.79
• Database API | Risk 72.16
• Search API | Risk 48.45

Business Units
• DevOps | Risk 100.0
• Identity | Risk 100.0
• Analytics | Risk 100.0
• HR | Risk 100.0
• Payments | Risk 100.0
• Finance | Risk 100.0
• CRM | Risk 100.0

Dependency Chains
Oracle → Admin Portal → Authorization API → HR
Oracle → Admin Portal → Billing API → Finance
Oracle → Admin Portal → File Upload API → DevOps
Oracle → Admin Portal → Analytics API → Analytics
Oracle → Admin Portal → Email API → Finance
Oracle → Admin Portal → Customer API → Identity
Oracle → Storage Platform → CRM API → Payments
Oracle → Storage Platform → Audit API → Payments
Oracle → Storage Platform → Search API → Analytics
Oracle → Storage Platform → User API → HR
Oracle → Search Platform → Database API → HR
Oracle → Search Platform → Payment API → CRM
Oracle → Search Platform → Admin API → Payments
Oracle → Search Platform → Storage API → Payments
Oracle → Search Platform → Authentication API → Analytics

In [235]:
def enterprise_ai(question):

    # -----------------------------
    # Detect Intent
    # -----------------------------

    intent = detect_intent(question)

    vendor = extract_vendor(question)

    # -----------------------------
    # Context Builder
    # -----------------------------

    if intent == "analytics":

        analytics = analytics_engine(question)

        if analytics is None:

            context = build_context(question)

        else:

            context = analytics.to_string(index=False)

    elif intent == "simulation":

        if vendor is None:

            return "Please specify a vendor to simulate an attack."

        context = simulation_summary(vendor)

    else:

        context = build_context(question)
    # -----------------------------
    # Confidence Score
    # -----------------------------

    confidence = "High"

    if intent == "analytics":
        confidence = "Very High"

    elif intent == "simulation":
        confidence = "Very High"

    elif len(context) < 1000:
        confidence = "Medium"

    elif len(context) < 300:
        confidence = "Low"
    # -----------------------------
    # Prompt
    # -----------------------------

    prompt = f"""
You are Enterprise Risk Radar AI.

You are an Enterprise Cyber Risk Intelligence Analyst.

Answer ONLY using the supplied enterprise knowledge.

Do NOT hallucinate.

If information is unavailable, explicitly say so.

Your report MUST follow this structure.

------------------------------------------------

Executive Summary

Evidence

Root Cause Analysis

Enterprise Dependency Analysis

Risk Propagation

Critical Applications

Critical APIs

Affected Business Units

Immediate Actions (0-24 hrs)

Short-Term Actions (7 Days)

Long-Term Actions (30 Days)

Priority

Confidence : {confidence}

------------------------------------------------

Enterprise Knowledge

{context}

------------------------------------------------

Question

{question}

------------------------------------------------

Instructions:

• Use propagated risks whenever available.

• If this is a simulation query, assume the attack has already occurred and explain downstream enterprise impact.

• If this is an analytics query (Top Vendors, Top APIs, Zombie APIs, Shadow APIs, Compliance, Financial etc.), summarize the dataframe provided and explain why those entities appear at the top.

• Never invent vendors, APIs or applications.

• Always justify recommendations using evidence from the supplied context.
"""

    # -----------------------------
    # Gemini Response
    # -----------------------------

    response = model.generate_content(prompt)

    return response.text

In [236]:
def detect_intent(question):

    q = question.lower()

    # ---------- Analytics ----------

    if any(x in q for x in [
        "top",
        "highest",
        "most",
        "lowest",
        "least",
        "rank",
        "ranking"
    ]):
        return "analytics"

    # ---------- Simulation ----------

    elif any(x in q for x in [
        "simulate",
        "simulation",
        "ransomware",
        "breach",
        "attack",
        "what if"
    ]):
        return "simulation"

    # ---------- Vendor ----------

    elif any(v.lower() in q for v in vendor_df["vendor"].tolist()):
        return "vendor"

    # ---------- API ----------

    elif any(x in q for x in [
        "api",
        "zombie",
        "shadow",
        "endpoint",
        "tls",
        "authentication"
    ]):
        return "api"

    # ---------- Compliance ----------

    elif "compliance" in q:
        return "compliance"

    # ---------- Graph ----------

    elif any(x in q for x in [
        "business unit",
        "propagation",
        "dependency",
        "application"
    ]):
        return "graph"

    elif "summary" in q or "posture" in q:
      return "analytics"

    return "general"

In [237]:
#Testing4:
print(
    enterprise_ai(
        "Why is Oracle High Risk?"
    )
)

------------------------------------------------

Executive Summary
Oracle is classified as a "High Risk" vendor with a Vendor Risk Score of 76.45. This elevated risk profile is primarily attributed to a substantial number of cybersecurity incidents (58), complemented by 18 operational, 4 compliance, and 1 financial event. The high propagated risk score of 76.45 for Oracle within the enterprise underscores its significant potential impact on critical applications, APIs, and multiple core business units including Payments, Finance, and CRM.

Evidence
*   **Vendor Risk Level:** High
*   **Vendor Risk Score:** 76.45
*   **Cybersecurity Incidents:** 58
*   **Operational Events:** 18
*   **Compliance Events:** 4
*   **Financial Events:** 1
*   **Propagated Risk (Enterprise Node: Oracle):** 76.45
*   **Propagated Risk (Enterprise Node: Oracle Cloud):** 32.16
*   **Related Headlines:** Oracle actively discusses cybersecurity threats ("CFOs and Cybersecurity: Top Threats and How to Prevent Them") and database security assessments ("Introducing DBSAT 3.1 integration with Enterprise Manager").

Root Cause Analysis
Oracle's high-risk status stems from a documented history of frequent cybersecurity incidents, which indicate potential vulnerabilities, frequent targeting, or challenges in maintaining a robust security posture across its offerings. The cumulative impact of operational, compliance, and financial events further compounds this risk, suggesting broader stability and governance concerns. Given its deep integration with critical enterprise applications and APIs, any compromise within Oracle's ecosystem has a significant potential for widespread propagation and impact across key business operations.

Enterprise Dependency Analysis
Oracle is a foundational vendor with extensive dependencies across the enterprise. It is directly connected to critical applications such as the Admin Portal, Storage Platform, and Search Platform. A wide array of essential APIs, including Admin API, CRM API, User API, Billing API, Payment API, Authorization API, Database API, and Search API, rely on Oracle. Consequently, its high-risk status directly impacts crucial business units including DevOps, Identity, Analytics, HR, Payments, Finance, and CRM.

Risk Propagation
*   **Enterprise Node: Oracle** - Propagated Risk: 76.45
*   **Enterprise Node: Oracle Cloud** - Propagated Risk: 32.16

Critical Applications
*   Admin Portal
*   Storage Platform
*   Search Platform

Critical APIs
*   Admin API
*   CRM API
*   User API
*   Billing API
*   File Upload API
*   Storage API
*   Analytics API
*   Authentication API
*   Customer API
*   Email API
*   Audit API
*   Payment API
*   Authorization API
*   Database API
*   Search API

Affected Business Units
*   DevOps
*   Identity
*   Analytics
*   HR
*   Payments
*   Finance
*   CRM

Immediate Actions (0-24 hrs)
*   **Enhanced Monitoring:** Activate heightened monitoring and logging for all Oracle-related network traffic, system access, and connected APIs, especially Payment API and Database API, to detect unusual activity immediately.
*   **Vulnerability Scan:** Initiate an emergency vulnerability scan and review for all enterprise systems directly integrated with Oracle, prioritizing critical applications like Admin Portal and Storage Platform.
*   **Incident Response Team Alert:** Notify the enterprise incident response team and relevant technical leads in affected business units (DevOps, Identity, Payments, Finance, CRM) of Oracle's high-risk status and potential for impact.
*   **Access Review:** Temporarily review and potentially restrict non-essential administrative access to Oracle-connected applications and highly sensitive APIs.

Short-Term Actions (7 Days)
*   **Security Configuration Audit:** Conduct a comprehensive security audit of all Oracle configurations and integrations, focusing on hardening measures and aligning with best practices to mitigate risks associated with the reported 58 cybersecurity incidents.
*   **Patch Management Review:** Review the patch management process for all Oracle products and dependent systems, ensuring all critical security updates are applied promptly.
*   **Access Control Review:** Re-evaluate and strengthen access controls and least privilege principles for all users and systems interacting with Oracle, particularly for critical APIs like Authorization API and Admin API, and for affected BUs like Identity and Finance.
*   **Dependency Mapping:** Complete a detailed mapping of all applications and services dependent on Oracle to better understand the full scope of potential impact and propagation paths.

Long-Term Actions (30 Days)
*   **Vendor Risk Management Program:** Formalize and implement a continuous vendor risk management program for Oracle, including regular security assessments, threat intelligence feeds, and performance metrics tracking all event categories (cybersecurity, operational, compliance, financial).
*   **Architectural Review for De-risking:** Explore architectural alternatives or compensating controls to reduce the enterprise's reliance on high-risk Oracle components, especially for functions handled by critical applications like Admin Portal and APIs like Payment API.
*   **Incident Response Playbook Enhancement:** Develop and test specific incident response playbooks tailored for scenarios involving a compromise of Oracle-dependent systems, involving all affected business units.
*   **Security Training:** Conduct targeted security awareness training for personnel in affected business units (DevOps, Identity, Payments, Finance) on common threats and secure practices related to Oracle systems.

Priority
High

Confidence : Medium

------------------------------------------------

In [208]:
response = model.generate_content("Hello")

print(response.text)

Hello! How can I help you today?

## Analytics Engine:

In [225]:
def analytics_engine(question):

    q = question.lower()

    # ---------- Vendors ----------

    if "top" in q and "vendor" in q:

        return vendor_df.sort_values(
            "risk_score",
            ascending=False
        ).head(10)

    if "cyber" in q and "vendor" in q:

        return vendor_df.sort_values(
            "Cybersecurity",
            ascending=False
        ).head(10)

    if "compliance" in q:

        return vendor_df.sort_values(
            "Compliance",
            ascending=False
        ).head(10)

    if "financial" in q:

        return vendor_df.sort_values(
            "Financial",
            ascending=False
        ).head(10)

    # ---------- APIs ----------

    if "api" in q and "top" in q:

        return api_df.sort_values(
            "risk_score",
            ascending=False
        ).head(10)

    if "zombie" in q:

        return api_df[
            api_df["status"]=="Zombie"
        ]

    if "shadow" in q:

        return api_df[
            api_df["status"]=="Shadow"
        ]

    return None
    if "enterprise cyber posture" in q or "cyber posture" in q:

      return vendor_df[
          [
              "vendor",
              "risk_score",
              "risk_level"
          ]
      ].sort_values(
          "risk_score",
          ascending=False
      )

In [226]:
def system_status():

    return {
        "Vendor Records": len(vendor_df),
        "News Articles": len(news_df),
        "APIs": len(api_df),
        "Applications": len(applications_df),
        "Enterprise Nodes": len(risk_df),
        "Knowledge Base": len(knowledge_base),
        "FAISS Documents": index.ntotal
    }

In [227]:
system_status()

{'Vendor Records': 36,
 'News Articles': 1568,
 'APIs': 533,
 'Applications': 108,
 'Enterprise Nodes': 685,
 'Knowledge Base': 2822,
 'FAISS Documents': 2822}

In [228]:
def executive_summary():

    top_vendor = vendor_df.sort_values(
        "risk_score",
        ascending=False
    ).iloc[0]

    zombie = len(
        api_df[
            api_df["status"]=="Zombie"
        ]
    )

    shadow = len(
        api_df[
            api_df["status"]=="Shadow"
        ]
    )

    critical = len(
        vendor_df[
            vendor_df["risk_level"]=="Critical"
        ]
    )

    return f"""

Enterprise Executive Summary

Total Vendors : {len(vendor_df)}

Critical Vendors : {critical}

Zombie APIs : {zombie}

Shadow APIs : {shadow}

Highest Risk Vendor : {top_vendor['vendor']}

Highest Risk Score : {top_vendor['risk_score']}

"""

In [229]:
print(executive_summary())

Enterprise Executive Summary

Total Vendors : 36

Critical Vendors : 3

Zombie APIs : 145

Shadow APIs : 20

Highest Risk Vendor : AWS

Highest Risk Score : 100.0

In [230]:
def suggested_questions():

    return [

        "Why is Oracle High Risk?",

        "Top 10 Risky Vendors",

        "Top 10 Risky APIs",

        "Show Zombie APIs",

        "Show Shadow APIs",

        "Highest Compliance Risk Vendors",

        "Highest Financial Risk Vendors",

        "Simulate ransomware attack on Oracle",

        "Which business units are affected by Oracle?",

        "Summarize enterprise cyber posture"

    ]

## DOWNLOADING ALL CSVs:

In [238]:
from google.colab import files
import os

csv_files = [
    "vendor_summary.csv",
    "master_news.csv",
    "api_inventory.csv",
    "enterprise_applications.csv",
    "enterprise_graph.csv",
    "enterprise_risk.csv"
]

for file in csv_files:
    if os.path.exists(file):
        print(f"Downloading {file}...")
        files.download(file)
    else:
        print(f"{file} not found. Skipping.")

Downloading vendor_summary.csv...

Downloading master_news.csv...

Downloading api_inventory.csv...

Downloading enterprise_applications.csv...

Downloading enterprise_graph.csv...

Downloading enterprise_risk.csv...

cyber_news.csv not found. Skipping.
financial_news.csv not found. Skipping.
operational_news.csv not found. Skipping.
compliance_news.csv not found. Skipping.